
project_id = "nklbbeavnbwvvatqimxw"

[functions.text-to-speech]
verify_jwt = true

[functions.tts-twillio-handler]
verify_jwt = false

[functions.test-audio-call]
verify_jwt = false

[functions.process-dialog]
verify_jwt = false

[functions.call-status]
verify_jwt = false

[functions.call-handler]
verify_jwt = false

[functions.twilio-echo]
verify_jwt = false

[functions.twilio-diagnostic]
verify_jwt = false

[functions.zenvia-call-handler]
verify_jwt = false

[functions.zenvia-process-dialog]
verify_jwt = false
