
project_id = "nklbbeavnbwvvatqimxw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[realtime]
enabled = true
port = 54329

[functions]
enabled = true
serve_port = 54330

[functions.campaign-executor]
verify_jwt = false

[functions.make-call]
verify_jwt = false

[functions.call-status]
verify_jwt = false

[functions.call-handler]
verify_jwt = false

[functions.call-record-status]
verify_jwt = false

[functions.setup-cron-job]
verify_jwt = true

[analytics]
enabled = false
port = 54331
vector_port = 54332
