
project_id = "your-project-id"

[functions.text-to-speech]
verify_jwt = true

[functions.tts-twillio-handler]
verify_jwt = false

[functions.test-audio-call]
verify_jwt = false

[functions.process-dialog]
verify_jwt = false

[functions.call-status]
verify_jwt = false
