
project_id = "nklbbeavnbwvvatqimxw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.conversation-relay-handler]
verify_jwt = false

[functions.ai-websocket-server]
verify_jwt = false

[functions.make-conversation-call]
verify_jwt = true

[functions.call-status]
verify_jwt = false

[functions.campaign-executor]
verify_jwt = true
