
project_id = "nklbbeavnbwvvatqimxw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
[functions.make-call]
verify_jwt = true
[functions.call-handler]
verify_jwt = true
[functions.call-status]
verify_jwt = true
[functions.call-record-status]
verify_jwt = true
[functions.call-record-callback]
verify_jwt = true
[functions.text-to-speech]
verify_jwt = true
[functions.campaign-executor]
verify_jwt = true
[functions.setup-cron-job]
verify_jwt = true
