// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nklbbeavnbwvvatqimxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbGJiZWF2bmJ3dnZhdHFpbXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Nzg1MjcsImV4cCI6MjA2MjI1NDUyN30.NkTQyDm7kLKJk075EBK1DIhcaUXLXx5gQip1bXet32M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);